# Generated by Django 4.0 on 2021-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santagame',
            name='game_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
